### ISSUE TITLE
JMessageClient.getUserInfo()传入中文参数抛出异常。

### ISSUE THREAD

**Issue by 923325596** [jpush/jmessage-api-java-client#49]
java.lang.IllegalArgumentException: The parameter username contains illegal character, a-zA-Z_0-9.、-,@。 is legally, and start with alphabet or number. Input is 中文

**Comment by helperhaps** [comment]
是的，username 不支持中文字符
```
username Byte(4-128) 支持字符
- 开头：字母或者数字
- 字母、数字、下划线
- 英文点、减号、@
```
